# Generated by Django 3.0.5 on 2024-11-14 17:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills_required', jsonfield.fields.JSONField(default=dict)),
                ('location', models.CharField(max_length=255)),
                ('experience_required', models.IntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('closed', 'closed')], max_length=10)),
            ],
        ),
    ]
