# Generated by Django 3.0.5 on 2024-12-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='jobs.Company'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='remote_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
